### ISSUE TITLE
Create Fulma.Toast 

### ISSUE THREAD

**Issue by MangelMaxime** [Fulma/Fulma#157]
Provide a ready to use package which implement `Thoth.Elmish.Toast` for Fulma.

I guess we will also need to create an npm package to deliver the `style.sass` file

**Comment by MangelMaxime** [comment]
With Fable 2, we now have the content of the `fable` folder copied from the package to the project directory.

If we include the `style.sass` in the package under `fable` then we should be able to access it for the sass compilation. 

The benefit is to have everything stored in a single place and not have to manage/keep in sync a nuget package and an npm package.

**Comment by realvictorprm** [comment]
I think this can be closed as it is solved with #168, right?

**Comment by MangelMaxime** [comment]
Well it seems like I never published it 🤣

Also, in reality  the `style.sass` file should go into an `npm` package in order to be easily accessible. 

So there still a few things to do first but thank you for the head up
