### ISSUE TITLE
Take class names from union values instead of string literals

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Fulma/Fulma#173]
Last time I was analyzing the bundle size of a Fulma app I noticed the library was still taking a considerable space. It seems that a big part of this are the string literals for the class names. Even if I recommended to use them #19 I realize now it's not always the best choice: string literals will be duplicated if called multiple times, and because all of them are always referenced, all the literals will be included in the bundle even if users don't need them (and some files like Column.fs have lots of strings).

However, as in Fable 2 case names of a union type can be tree shaken if not used, taking the class names from the union values may help reducing the final bundle size. In Fable 2.1, [`getCaseName` has been added](https://github.com/fable-compiler/Fable/blob/f606721155b8ea9447697321fecac9b5175cfa0e/src/dotnet/Fable.Core/Fable.Core.Reflection.fs#L7) so you can take the case name without the full reflection info for the type.

I haven't made any measure to check the impact. But I can try to make a quick test if you agree with the proposal.

**Comment by MangelMaxime** [comment]
So this means we would replace:

```fs
    let ofColor level =
        match level with
        | IsBlack -> Classes.IsBlack
        | IsDark -> Classes.IsDark
        | IsLight -> Classes.IsLight
        | IsWhite -> Classes.IsWhite
        | IsPrimary -> Classes.IsPrimary
        | IsInfo -> Classes.IsInfo
        | IsSuccess -> Classes.IsSuccess
        | IsWarning -> Classes.IsWarning
        | IsDanger -> Classes.IsDanger
        | IsLink -> Classes.IsLink
        | IsBlackBis -> Classes.IsBlackBis
        | IsBlackTer -> Classes.IsBlackTer
        | IsGreyDarker -> Classes.IsGreyDarker
        | IsGreyDark -> Classes.IsGreyDark
        | IsGrey -> Classes.IsGrey
        | IsGreyLight -> Classes.IsGreyLight
        | IsGreyLighter -> Classes.IsGreyLighter
        | IsWhiteTer -> Classes.IsWhiteTer
        | IsWhiteBis -> Classes.IsWhiteBis
        | IsCustomColor color -> "is-" + color
        | NoColor -> ""
```

with something like:

```fs
CaseA.getCaseName
```

?

-----

Don't test it yet :), I am putting this notes so we/I can remember them

If we wants to test the effects we should test it on `fulma-demo` and `Fulma doc site` to see if bundles size decrease for "normal" application and for application that "heavily" use Fulma.

**Comment by alfonsogarciacaro** [comment]
Yes, more or less that's the idea :) Of course there will still be special cases to handle like `IsCustomColor`.

**Comment by MangelMaxime** [comment]
If we improve the bundles and have no breaking change I don't see any reason to not try it :)

Can you please test it on `Button` and `Columns` modules ? 

`Button` because it's a module with use more or less all the possibilities of `Fulma`. And `Columns`, because it probably the module which have the more to gain from it. :)
