### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [fulma/Fulma#191]
The link for the documentation in the project description is giving a 404

https://mangelmaxime.github.io/Fulma/

![image](https://user-images.githubusercontent.com/1881570/51999983-00dbc380-248a-11e9-9907-924b80d432a2.png)

**Comment by MangelMaxime** [comment]
Thank you I fixed it.

The link is now: https://fulma.github.io/Fulma/
