### ISSUE TITLE
Question template: update?

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#195]
Is the template still in use (in which case I would update it) or is this archived?

**Comment by MangelMaxime** [comment]
Still in use, but my different project are more or less in pause until I finish the docs generator and the split of in different repos.

This actions, will help improve user experience, make the contribution easier and also help me maintain the project more easily.

**Comment by selketjah** [comment]
Ok, I guess I will wait so I don't have to redo it again :)
thank you for answering
