### ISSUE TITLE
Navbar.burger options

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Fulma/Fulma#212]
It's a bit difficult to add a click event to Navbar.burger right now:

```fsharp
  Navbar.burger
    [ if state.current.IsActive then
        yield GenericOption.CustomClass "is-active"
      yield GenericOption.Props [ OnClick (fun _ ->
        state.update {| IsActive = not state.current.IsActive |}) ] ]
    [ span [ ] [ ]
      span [ ] [ ]
      span [ ] [ ] ]
```

There should be an `IsActive` (as for Navbar.menu) and `OnClick` options, so we can write something like this:

```fsharp
  Navbar.burger
    [ Navbar.Burger.IsActive state.current.IsActive
      Navbar.Burger.OnClick (fun _ ->
        state.update {| IsActive = not state.current.IsActive |}) ]
```

**Comment by MangelMaxime** [comment]
I agree `IsActive` should take a `bool` as an argument. It already the case for others `IsActive`.

As a side note you don't need to use the `GenericOption` prefix.

**Comment by MangelMaxime** [comment]
Version 2.7.0 include the new Navbar.Burger.Option
