### ISSUE TITLE
Using actual button elements for pagination buttons

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Fulma/Fulma#228]
For the pagination buttons (next, previous, link, ellipsis), Fulma is generating `a` HTML elements.

https://github.com/Fulma/Fulma/blob/0e7119cae66cf0f517a7cbf21e543235554975e6/src/Fulma/Components/Pagination.fs#L46-L73

This probably follows [Bulma documentation samples](https://bulma.io/documentation/components/pagination/). However we found a problem with this: when adding the `Disabled` attribute to some of the buttons (a very common operation) the browsers don't block the `OnClick` event which is against the expectation of the developer and usually cause problems if the user clicks the disabled element.

When generating actual `button` elements, the styling seems to stay the same and the element behaves as expected when disabled (blocking the `onclick`). Maybe we should do that instead?

**Comment by MangelMaxime** [comment]
This seems indeed a good idea :)

**Comment by MangelMaxime** [comment]
Should be fixed in version 2.2.0.
