### ISSUE TITLE
Documentation pagination: renders as `a` but the code shows `button`

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#234]
According to the code in github, `previous`, `next`, `link` and `ellipsis` are being rendered as buttons instead, which was requested in #228 

https://github.com/Fulma/Fulma/blob/master/src/Fulma/Components/Pagination.fs#L46

But the documentation still renders them as `a` tags for some reason.

<img width="439" alt="Screenshot 2019-11-05 at 17 06 49" src="https://user-images.githubusercontent.com/2250570/68224381-c7268300-ffee-11e9-9c3d-7984ac6e116c.png">

https://fulma.github.io/Fulma/#fulma/components/pagination

**Comment by MangelMaxime** [comment]
That's because when fixing #228, we used `button` only for `previous`, `next` and `ellipsis`.

`link` element is still using `a` as the container element.

Version `2.3.0` should fix this problem.

Updated documentation should be available soon.
