### ISSUE TITLE
GenericOption vs Option list for Pagination

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#243]
There is a difference between `previous`, `next` and `link` on how to dispatch a redirect.
It is a bit confusing for the users of the library.

Is there something we could do for this?

```
Pagination.pagination [ ] [
            Pagination.previous [ Props [ OnClick (fun _ -> previousPage |> Redirect |> dispatch) ] ] [ str "Previous" ]
            Pagination.next [ Props [ OnClick (fun _ -> nextPage |> Redirect |> dispatch) ]  ] [ str "Next" ]
            Pagination.list [ ] [
                Pagination.link [ Pagination.Link.Props [ OnClick (fun _ -> number |> Redirect |> dispatch) ] ] [ str text ]
            ]
        ]
```

**Comment by MangelMaxime** [comment]
Unfortunately there not much we can do here.

The only "solution", would be to make `Pagination.previous` and `Pagination.next` not use the `GenericOption` but a "custom" option with exactly the same feature as the `GenericOption`.

If we do that, we are creating a new special case, which exist nowhere else in the library. For me both, situation have their pros and cons and I prefer to keep it without special case.

Please feel free to comment more on this issue, if you have another solution.
