### ISSUE TITLE
Update FontAwesome

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#246]
FontAwesome now has Duotone for pro
Would be a good moment to update.

But they changed their website again... It is now url based division of the different types.

Example PRO: https://fontawesome.com/cheatsheet/pro/solid
Example Free: https://fontawesome.com/cheatsheet/free/solid

**Comment by MangelMaxime** [comment]
Version 2.1.0 for Fable.FontAwesome.Free and Fable.FontAwesome.Pro has been released.

Their update was not that bad this time :)
