### ISSUE TITLE
File has specific area that opens the pop-up

### ISSUE THREAD

**Issue by selketjah** [Fulma/Fulma#250]
**Fulma vs Bulma when clicking** 

![2020-03-26 10 55 18](https://user-images.githubusercontent.com/2250570/77634463-47736380-6f51-11ea-8a45-6b7f9553a675.gif)

**Fulma html**
<img width="470" alt="Screenshot 2020-03-26 at 11 01 03" src="https://user-images.githubusercontent.com/2250570/77634514-63770500-6f51-11ea-80b4-dad1318e5f30.png">

**Bulma html**
<img width="623" alt="Screenshot 2020-03-26 at 11 00 31" src="https://user-images.githubusercontent.com/2250570/77634544-6c67d680-6f51-11ea-9035-b8c670a92140.png">

**Comment by MangelMaxime** [comment]
Indeed, the fix is to transform `File.label` allowing control of the output element `File.Label.label`, `File.Label.span`
