### ISSUE TITLE
Fulma.Extensions.Wikiki.Tooltip doesn't work correctly

### ISSUE THREAD

**Issue by TPLeon** [Fulma/Fulma#254]
It seems that the Tooltip extension doesn't work. I followed the steps as given on https://fulma.github.io/Fulma/#fulma-extensions/tooltip.

See here min repro:
https://gitlab.com/leontrueprice/tooltip-testing-for-maxime 

Are others encountering similar problems?

**Comment by MangelMaxime** [comment]
Hello,

you need to include the `bulma-tooltip` files in your [`style.scss`](https://gitlab.com/leontrueprice/tooltip-testing-for-maxime/-/blob/master/src/Client/style.scss#L16)

[Example](https://github.com/Fulma/Fulma/blob/master/docs/scss/main.scss#L42)

**Comment by TPLeon** [comment]
Thank you @MangelMaxime! Works perfectly. Is there a reason for it not to be necessary for the checkradio extension?

**Comment by MangelMaxime** [comment]
It should be required for all the extension in theory.

But perhaps, the author of the extensions made something special for it but I don't think it is possible to have them included "magically".

**Comment by TPLeon** [comment]
Ok, clear! Thanks
