### ISSUE TITLE
Method not found: 'Void Console.warn(Microsoft.FSharp.Core.FSharpOption`1<System.Object>, System.Object[])'.

### ISSUE THREAD

**Issue by forki** [Fulma/Fulma#294]
I'm trying to update to .NET 6 and I'm getting:

      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'Void Console.warn(Microsoft.FSharp.Core.FSharpOption`1<System.Object>, System.Object[])'.
         at Fulma.Modifier.parseModifiers@582.Invoke(FSharpList`1 result, IModifier option)
         at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in D:\a\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 221
         at Fulma.Common.GenericOptions.AddModifiers(FSharpList`1 modifiers)
         at Fulma.Container.parseOptions@24-57.Invoke(GenericOptions result, Option option)
         at Fulma.Container.container(FSharpList`1 options, FSharpList`1 children)

**Comment by forki** [comment]
@alfonsogarciacaro @MangelMaxime

Now that .NET 6.0.200 is released, I'd love to update. This issue seems to be the last blocker. Any ideas what we can do?

**Comment by alfonsogarciacaro** [comment]
@forki Is this code for SSR, so run on .NET? Looking at the history of Fable.Core.JS it looks I [removed some overloads](https://github.com/fable-compiler/Fable/commit/949af92f5078a8275a695cd4ca1d3d285e1e8a44) thinking they were unnecessary but they cause issues when run on .NET (and oddly enough only with dotnet/fsharp 6). I can think of the following solutions:

- You can pin Fable.Core to 3.4 in your project (the version before the overloads were removed)
- Release a new version of Fulma compiled with Fable 3.6 as dependency
- Release a new version of Fable.Core adding back the overloads

**Comment by forki** [comment]
Yes it's the SSR part. Personally I'd prefer a forward strategy i.e. reading the overloads and pushing a new version of Fable.Core

**Comment by alfonsogarciacaro** [comment]
Ok, I've published Fable.Core 3.6.2 with those changes reverted 👍 Can you please check?

**Comment by forki** [comment]
thanks a lot! this seems to work!

**Comment by MangelMaxime** [comment]
Thank you @alfonsogarciacaro 

I am also releasing a new version of Fulma to fix the message because the strings are not build correctly.
