### ISSUE TITLE
Add snippets/samples section to docs

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Fulma/Fulma#90]
The documentation for components and extensions is totally. It would be also great if there is a snippets/samples section where users can easily PR a snippet (for example, a login box) and then the docs were automatically updated so other users could see the result of the code as well as the source code. That would allow the community to create a catalog of Fulma snippets they can easily copy, paste and edit into their projects 😃

**Comment by kunjee17** [comment]
@MangelMaxime this would be fun. It will encourage more people to come up with Fulma specific components (other than extension)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I am not sure to understand what you want ?

We can indeed add a new section/page to host snippets with code + preview + search. But what do you mean by: 

> and then the docs were automatically updated so other users could see the result of the code as well as the source code

**Comment by alfonsogarciacaro** [comment]
A snippet section with code + preview + search would be great!

I was only thinking that it was important that users can easily submit their own snippets, so it's not only you who has to write all the samples. I'm not sure yet what's the best/easiest way though. Maybe for now users could send a PR and then there'd be a FAKE target to rebuild the docs and include the new snippets (something similar to the browser samples).

**Comment by MangelMaxime** [comment]
Ok I see.

I will thin about that. We already have the FAKE targets to builds the docs site and publish it. So, the work needed is on where to add them, and how etc. I have some ideas, and will work on it after the next version of Fulma which will lead to some breaking change so. Better to wait for it before asking snippet otherwise someone would need to convert them :)

**Comment by MangelMaxime** [comment]
I think it will not happen so I am closing this issue
