### ISSUE TITLE
Provide a form abstraction

### ISSUE THREAD

**Issue by MangelMaxime** [Fulma/Fulma#96]
Provide a form abstraction with validation support.

References: 

- https://twitter.com/thewhitetigle/status/944256153390927872
- https://twitter.com/alfonsogcnunez/status/951011512851845120

**Important**, at first the form abstraction layer will try to be part of **Thot** project. The idea, is to provide a common library to support any CSS framework. In order to archive that, the API will based itself on accepting/rendering `React.HTMLElement`.

I will link to a prototype when ready.

**Comment by MangelMaxime** [comment]
The idea behind this choice, is people will only need to implement the renderer API contracts. Which will describe how to render an input, a field, a control, errors, etc.

**Comment by MangelMaxime** [comment]
I made some experimentation:

https://goo.gl/x9XmVQ

From user point of view here is how to hook a form in his application:

```fs
type Model =
    { FormState : Form.Builder<Msg> }

and Msg =
    | OnFormMsg of Form.Msg

let form = 
    Form.create OnFormMsg
    |> Form.addInputField
        ( Form.InputField.create ()
            |> Form.InputField.withLabel "Firstname")
    |> Form.addInputField
        ( Form.InputField.create ()
            |> Form.InputField.withLabel "Surname")
    |> Form.addInputField
        ( Form.InputField.create ()
            |> Form.InputField.withLabel "Email")


let init () = { FormState = form }, Cmd.none

// UPDATE

let update (msg:Msg) (model:Model) =
    match msg with
    | OnFormMsg msg ->
        { model with FormState = Form.update msg model.FormState }, Cmd.none

// VIEW (rendered with React)

let view model dispatch =
    div [ Class "container" ]
        [ div [ Class "row" ]
            [ div [ Class "column column-50 column-offset-25"]
                [ Form.render model.FormState dispatch ] ] ]

// App
Program.mkProgram init update view
|> Program.withConsoleTrace
|> Program.withReact "elmish-app"
|> Program.run
```

![2018-09-27 12 49 38](https://user-images.githubusercontent.com/4760796/46141332-f13a3d00-c253-11e8-8e7f-c46635618b9b.gif)

The idea is to store all the information in a record and let the user provide the different `render` methods. Like that he can use any CSS framework on top of it.

**Comment by whitetigle** [comment]
I think this is a very very very good idea!

**Comment by MangelMaxime** [comment]
*Update*

[FormBuilder](https://mangelmaxime.github.io/Thoth/elmish/FormBuilder.html) has been released.

It doesn't have yet a strong Fulma support but will be coming.

**Comment by MangelMaxime** [comment]
Fable.Form now fill in largely this goal
